project:
  type: website

website:
  title: "PhD project"
  navbar:
    left:
      - href: map.qmd
        text: Sample map

format:
  html:
    page-layout: full
    code-fold: true
    code-summary: "Show the code"
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

