project:
  type: website

website:
  title: "Sample_map_M.arvalis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: map.qmd
        text: Sample map

format:
  html:
    page-layout: full
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

